const products = [
  {
    name: 'Wireless Noise-Canceling Studio Headphones',
    description: 'Precision-engineered over-ear acoustic headphones with active hybrid noise cancellation, 40mm titanium dynamic drivers, and 36-hour battery playback for immersive listening.',
    price: 249.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    category: 'Electronics',
    stock: 25,
    averageRating: 4.8,
    numOfReviews: 12,
  },
  {
    name: 'Mechanical Tactile Typing Keyboard',
    description: 'Custom hot-swappable mechanical keyboard with solid aluminum casing, pre-lubed tactile switches, PBT double-shot keycaps, and programmable RGB backlighting.',
    price: 139.5,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
    category: 'Electronics',
    stock: 18,
    averageRating: 4.7,
    numOfReviews: 9,
  },
  {
    name: 'Minimalist Matte Ceramic Coffee Mug Set',
    description: 'Handcrafted stoneware ceramic mugs with tactile matte glaze, 350ml capacity, and ergonomic handles. Microwave and dishwasher safe.',
    price: 42.0,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
    category: 'Kitchen',
    stock: 40,
    averageRating: 4.9,
    numOfReviews: 15,
  },
  {
    name: 'Full-Grain Vegetable Tanned Leather Wallet',
    description: 'Handcrafted bifold cardholder made from Tuscan vegetable-tanned leather. Holds up to 8 cards and cash with RFID-blocking interior lining.',
    price: 68.0,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
    category: 'Accessories',
    stock: 30,
    averageRating: 4.6,
    numOfReviews: 8,
  },
  {
    name: 'Solid Walnut Ergonomic Desk Shelf',
    description: 'Elevated dual-monitor desk riser crafted from American solid walnut hardwood and powder-coated steel legs. Includes cable management routing.',
    price: 185.0,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80',
    category: 'Furniture',
    stock: 12,
    averageRating: 4.9,
    numOfReviews: 14,
  },
  {
    name: 'Classic Automatic Minimalist Watch',
    description: 'Sapphire crystal glass dial with Japanese self-winding automatic movement, 316L stainless steel case, and interchangeable Italian leather strap.',
    price: 295.0,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    category: 'Watch',
    stock: 15,
    averageRating: 4.8,
    numOfReviews: 11,
  },
  {
    name: 'Hardcover Linen Dot-Grid Notebook',
    description: '192 numbered pages of 120gsm ink-proof bleed-resistant paper bound in archival Belgian woven bookcloth with expandable back pocket.',
    price: 28.0,
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&q=80',
    category: 'Stationery',
    stock: 50,
    averageRating: 4.7,
    numOfReviews: 7,
  },
  {
    name: 'Cold-Brew Glass Dripper & Server',
    description: 'Borosilicate glass slow-drip iced coffee extraction system with micro-mesh stainless steel filter and precision flow-control valve.',
    price: 89.0,
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&q=80',
    category: 'Kitchen',
    stock: 20,
    averageRating: 4.9,
    numOfReviews: 16,
  },
  {
    name: 'Cast Iron Enameled Dutch Oven 5.5 Qt',
    description: 'Heavyweight enameled cast iron casserole pot for superior heat retention and uniform distribution. Oven safe up to 500°F with stainless knob.',
    price: 145.0,
    image: 'https://images.unsplash.com/photo-1584990347449-35c918c57500?w=800&q=80',
    category: 'Kitchen',
    stock: 14,
    averageRating: 4.8,
    numOfReviews: 10,
  },
  {
    name: 'Precision Aluminum Laptop Stand',
    description: 'CNC-machined aluminum alloy ergonomic laptop riser with silicone anti-slip pads and open-air thermal cooling airflow.',
    price: 54.0,
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=80',
    category: 'Electronics',
    stock: 35,
    averageRating: 4.6,
    numOfReviews: 6,
  },
  {
    name: 'Aerodynamic Automotive Phone Mount',
    description: 'Aircraft-grade anodized aluminum magnetic car air-vent mount with dual-axis 360-degree rotation and high-strength neodymium magnets.',
    price: 36.0,
    image: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800&q=80',
    category: 'Automative',
    stock: 28,
    averageRating: 4.5,
    numOfReviews: 5,
  },
  {
    name: 'Artisanal Organic Single-Origin Espresso Beans',
    description: '100% Arabica washed whole beans roasted in small batches with tasting notes of dark cocoa, toasted hazelnut, and sweet berry finish.',
    price: 22.0,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80',
    category: 'FOOD ingredients',
    stock: 60,
    averageRating: 5.0,
    numOfReviews: 22,
  },
];

module.exports = products;
